[package]
name = "model-test-tech"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
approx = "0.5"
anyhow = "1.0.99"
flate2 = "1.1.2"
indicatif = "0.18.0"
clap = { version = "4.5.45", features = ["derive"] }
